server:
  port: 8761

spring:
  cloud:
    gatewa
  application:
    name: service-registry

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost