server:
  port: 8091

# MySQL DataSource configuration
spring:
  application:
    name: question-service
  datasource:
    url: jdbc:mysql://localhost:3306/questiondb
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
